// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen5 = NULL;lv_obj_t *ui_SkyPanel = NULL;lv_obj_t *ui_targettonight = NULL;lv_obj_t *ui_Spinner1 = NULL;lv_obj_t *ui_guidingchart = NULL;lv_obj_t *ui_hfronly = NULL;lv_obj_t *ui_filtername = NULL;lv_obj_t *ui_totaldone = NULL;lv_obj_t *ui_Label14 = NULL;lv_obj_t *ui_hfrstat = NULL;lv_obj_t *ui_totstat = NULL;lv_obj_t *ui_batbar3 = NULL;lv_obj_t *ui_totstat1 = NULL;lv_obj_t *ui_meridian = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label10 = NULL;
// event funtions
void ui_event_SkyPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen1_screen_init);
}
}

// build funtions

void ui_Screen5_screen_init(void)
{
ui_Screen5 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SkyPanel = lv_obj_create(ui_Screen5);
lv_obj_set_width( ui_SkyPanel, 593);
lv_obj_set_height( ui_SkyPanel, 438);
lv_obj_set_x( ui_SkyPanel, -1 );
lv_obj_set_y( ui_SkyPanel, -1 );
lv_obj_set_align( ui_SkyPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SkyPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_targettonight = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_targettonight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_targettonight, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_targettonight, 0 );
lv_obj_set_y( ui_targettonight, -196 );
lv_obj_set_align( ui_targettonight, LV_ALIGN_CENTER );
lv_label_set_text(ui_targettonight,"DON'T LOOK UP");
lv_obj_set_style_text_font(ui_targettonight, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner1 = lv_spinner_create(ui_Screen5,1000,90);
lv_obj_set_width( ui_Spinner1, 225);
lv_obj_set_height( ui_Spinner1, 206);
lv_obj_set_x( ui_Spinner1, -150 );
lv_obj_set_y( ui_Spinner1, 98 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_guidingchart = lv_chart_create(ui_Screen5);
lv_obj_set_width( ui_guidingchart, 200);
lv_obj_set_height( ui_guidingchart, 100);
lv_obj_set_x( ui_guidingchart, -147 );
lv_obj_set_y( ui_guidingchart, -98 );
lv_obj_set_align( ui_guidingchart, LV_ALIGN_CENTER );
lv_chart_set_type( ui_guidingchart, LV_CHART_TYPE_LINE);
lv_chart_set_axis_tick( ui_guidingchart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_guidingchart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_guidingchart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_chart_series_t* ui_guidingchart_series_1 = lv_chart_add_series(ui_guidingchart, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_guidingchart_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_guidingchart, ui_guidingchart_series_1, ui_guidingchart_series_1_array);

ui_hfronly = lv_chart_create(ui_Screen5);
lv_obj_set_width( ui_hfronly, 200);
lv_obj_set_height( ui_hfronly, 100);
lv_obj_set_x( ui_hfronly, 147 );
lv_obj_set_y( ui_hfronly, -96 );
lv_obj_set_align( ui_hfronly, LV_ALIGN_CENTER );
lv_chart_set_type( ui_hfronly, LV_CHART_TYPE_LINE);
lv_chart_set_axis_tick( ui_hfronly, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_hfronly, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_hfronly, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_chart_series_t* ui_hfronly_series_1 = lv_chart_add_series(ui_hfronly, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_hfronly_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_hfronly, ui_hfronly_series_1, ui_hfronly_series_1_array);

ui_filtername = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_filtername, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_filtername, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_filtername, 0 );
lv_obj_set_y( ui_filtername, -168 );
lv_obj_set_align( ui_filtername, LV_ALIGN_CENTER );
lv_label_set_text(ui_filtername,"Filter");
lv_obj_set_style_text_font(ui_filtername, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_totaldone = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_totaldone, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_totaldone, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_totaldone, -159 );
lv_obj_set_y( ui_totaldone, 128 );
lv_obj_set_align( ui_totaldone, LV_ALIGN_CENTER );
lv_label_set_text(ui_totaldone,"0");
lv_obj_set_style_text_font(ui_totaldone, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, -158 );
lv_obj_set_y( ui_Label14, 85 );
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"subs done");
lv_obj_set_style_text_font(ui_Label14, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hfrstat = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_hfrstat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hfrstat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hfrstat, 120 );
lv_obj_set_y( ui_hfrstat, 73 );
lv_obj_set_align( ui_hfrstat, LV_ALIGN_CENTER );
lv_label_set_text(ui_hfrstat,"HFR: 0");
lv_obj_set_style_text_font(ui_hfrstat, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_totstat = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_totstat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_totstat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_totstat, 120 );
lv_obj_set_y( ui_totstat, 20 );
lv_obj_set_align( ui_totstat, LV_ALIGN_CENTER );
lv_label_set_text(ui_totstat,"Tot: 0\"");
lv_obj_set_style_text_font(ui_totstat, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batbar3 = lv_bar_create(ui_Screen5);
lv_bar_set_value(ui_batbar3,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_batbar3, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_batbar3, 37);
lv_obj_set_height( ui_batbar3, 10);
lv_obj_set_x( ui_batbar3, 264 );
lv_obj_set_y( ui_batbar3, -205 );
lv_obj_set_align( ui_batbar3, LV_ALIGN_CENTER );

ui_totstat1 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_totstat1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_totstat1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_totstat1, 128 );
lv_obj_set_y( ui_totstat1, 123 );
lv_obj_set_align( ui_totstat1, LV_ALIGN_CENTER );
lv_label_set_text(ui_totstat1,"Time to meridian");
lv_obj_set_style_text_font(ui_totstat1, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_meridian = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_meridian, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_meridian, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_meridian, 124 );
lv_obj_set_y( ui_meridian, 165 );
lv_obj_set_align( ui_meridian, LV_ALIGN_CENTER );
lv_label_set_text(ui_meridian,"0:00:00");
lv_obj_set_style_text_color(ui_meridian, lv_color_hex(0x00D106), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_meridian, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_meridian, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -249 );
lv_obj_set_y( ui_Label7, -171 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Total error");

ui_Label10 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 240 );
lv_obj_set_y( ui_Label10, -171 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"HFR graph");

lv_obj_add_event_cb(ui_SkyPanel, ui_event_SkyPanel, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
   if (ui_Screen5) lv_obj_del(ui_Screen5);

// NULL screen variables
ui_Screen5= NULL;
ui_SkyPanel= NULL;
ui_targettonight= NULL;
ui_Spinner1= NULL;
ui_guidingchart= NULL;
ui_hfronly= NULL;
ui_filtername= NULL;
ui_totaldone= NULL;
ui_Label14= NULL;
ui_hfrstat= NULL;
ui_totstat= NULL;
ui_batbar3= NULL;
ui_totstat1= NULL;
ui_meridian= NULL;
ui_Label7= NULL;
ui_Label10= NULL;

}
