// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen4 = NULL;lv_obj_t *ui_FocuserPanel = NULL;lv_obj_t *ui_ambientarc = NULL;lv_obj_t *ui_cameraarc = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_cfbutton = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_ambienttemp = NULL;lv_obj_t *ui_cameratemp = NULL;
// event funtions
void ui_event_FocuserPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen5_screen_init);
}
}

void ui_event_cfbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      cfbuttonpressed( e );
}
}

// build funtions

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FocuserPanel = lv_obj_create(ui_Screen4);
lv_obj_set_width( ui_FocuserPanel, 593);
lv_obj_set_height( ui_FocuserPanel, 438);
lv_obj_set_x( ui_FocuserPanel, -1 );
lv_obj_set_y( ui_FocuserPanel, -1 );
lv_obj_set_align( ui_FocuserPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FocuserPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ambientarc = lv_arc_create(ui_Screen4);
lv_obj_set_width( ui_ambientarc, 251);
lv_obj_set_height( ui_ambientarc, 317);
lv_obj_set_x( ui_ambientarc, -148 );
lv_obj_set_y( ui_ambientarc, 20 );
lv_obj_set_align( ui_ambientarc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ambientarc, -20,100);
lv_arc_set_value(ui_ambientarc, 15);
lv_obj_set_style_arc_width(ui_ambientarc, 25, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_ambientarc, 25, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_cameraarc = lv_arc_create(ui_Screen4);
lv_obj_set_width( ui_cameraarc, 250);
lv_obj_set_height( ui_cameraarc, 317);
lv_obj_set_x( ui_cameraarc, 147 );
lv_obj_set_y( ui_cameraarc, 20 );
lv_obj_set_align( ui_cameraarc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_cameraarc, -20,100);
lv_arc_set_value(ui_cameraarc, 15);
lv_obj_set_style_arc_width(ui_cameraarc, 25, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_cameraarc, 25, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -146 );
lv_obj_set_y( ui_Label8, -170 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Ambient temp");
lv_obj_set_style_text_font(ui_Label8, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 149 );
lv_obj_set_y( ui_Label1, -170 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Sensor temp");
lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cfbutton = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_cfbutton, 294);
lv_obj_set_height( ui_cfbutton, 96);
lv_obj_set_x( ui_cfbutton, -12 );
lv_obj_set_y( ui_cfbutton, 167 );
lv_obj_set_align( ui_cfbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cfbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_cfbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -13 );
lv_obj_set_y( ui_Label9, 168 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"C/F");
lv_obj_set_style_text_font(ui_Label9, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ambienttemp = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_ambienttemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ambienttemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ambienttemp, -149 );
lv_obj_set_y( ui_ambienttemp, -15 );
lv_obj_set_align( ui_ambienttemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_ambienttemp,"n/a");
lv_obj_set_style_text_font(ui_ambienttemp, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cameratemp = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_cameratemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cameratemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cameratemp, 145 );
lv_obj_set_y( ui_cameratemp, -15 );
lv_obj_set_align( ui_cameratemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_cameratemp,"n/a");
lv_obj_set_style_text_font(ui_cameratemp, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_FocuserPanel, ui_event_FocuserPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_cfbutton, ui_event_cfbutton, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
   if (ui_Screen4) lv_obj_del(ui_Screen4);

// NULL screen variables
ui_Screen4= NULL;
ui_FocuserPanel= NULL;
ui_ambientarc= NULL;
ui_cameraarc= NULL;
ui_Label8= NULL;
ui_Label1= NULL;
ui_cfbutton= NULL;
ui_Label9= NULL;
ui_ambienttemp= NULL;
ui_cameratemp= NULL;

}
