// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen6 = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_Button3 = NULL;lv_obj_t *ui_Label12 = NULL;
// event funtions
void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_uiGraphPanel, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_uiGraphPanel_screen_init);
}
}

// build funtions

void ui_Screen6_screen_init(void)
{
ui_Screen6 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image3 = lv_img_create(ui_Screen6);
lv_img_set_src(ui_Image3, &ui_img_c925sls_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 600
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 450
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel3 = lv_obj_create(ui_Screen6);
lv_obj_set_width( ui_Panel3, 589);
lv_obj_set_height( ui_Panel3, 46);
lv_obj_set_x( ui_Panel3, -1 );
lv_obj_set_y( ui_Panel3, -180 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, 3 );
lv_obj_set_y( ui_Label11, -1 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Connect to NINA-Display WIFI  and open 192.168.4.1 for initial setup ");

ui_Button3 = lv_btn_create(ui_Screen6);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 50);
lv_obj_set_x( ui_Button3, 234 );
lv_obj_set_y( ui_Button3, 177 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"OK");

lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
   if (ui_Screen6) lv_obj_del(ui_Screen6);

// NULL screen variables
ui_Screen6= NULL;
ui_Image3= NULL;
ui_Panel3= NULL;
ui_Label11= NULL;
ui_Button3= NULL;
ui_Label12= NULL;

}
