// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t *ui_Screen4;
extern void ui_event_FocuserPanel( lv_event_t * e);
extern lv_obj_t *ui_FocuserPanel;
extern lv_obj_t *ui_ambientarc;
extern lv_obj_t *ui_cameraarc;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label1;
extern void ui_event_cfbutton( lv_event_t * e);
extern lv_obj_t *ui_cfbutton;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_ambienttemp;
extern lv_obj_t *ui_cameratemp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

