// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Slider1 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Slider2 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Button4 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_sure1 = NULL;lv_obj_t *ui_sure2 = NULL;lv_obj_t *ui_batterybar = NULL;lv_obj_t *ui_batterylabel = NULL;lv_obj_t *ui_batbar1 = NULL;lv_obj_t *ui_BtnRig = NULL;lv_obj_t *ui_LabelRig = NULL;lv_obj_t *ui_riglabel = NULL;
// event funtions
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_uiGraphPanel, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_uiGraphPanel_screen_init);
}
}

void ui_event_Slider1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      xscalechange( e );
}
}

void ui_event_Slider2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      brigtnesschange( e );
}
}

void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      resetwifi( e );
}
}

void ui_event_BtnRig( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      switchrig( e );
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button2 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button2, 100);
lv_obj_set_height( ui_Button2, 50);
lv_obj_set_x( ui_Button2, -12 );
lv_obj_set_y( ui_Button2, 185 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -11 );
lv_obj_set_y( ui_Label3, 188 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"OK");
lv_obj_set_style_text_font(ui_Label3, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider1 = lv_slider_create(ui_Screen2);
lv_slider_set_value( ui_Slider1, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 437);
lv_obj_set_height( ui_Slider1, 29);
lv_obj_set_x( ui_Slider1, 1 );
lv_obj_set_y( ui_Slider1, -145 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );

ui_Label4 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 0 );
lv_obj_set_y( ui_Label4, -187 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"X-scale for guiding");
lv_obj_set_style_text_font(ui_Label4, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider2 = lv_slider_create(ui_Screen2);
lv_slider_set_value( ui_Slider2, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider2)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider2, 437);
lv_obj_set_height( ui_Slider2, 29);
lv_obj_set_x( ui_Slider2, 4 );
lv_obj_set_y( ui_Slider2, -37 );
lv_obj_set_align( ui_Slider2, LV_ALIGN_CENTER );

ui_Label5 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -5 );
lv_obj_set_y( ui_Label5, -87 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Screen brightness");
lv_obj_set_style_text_font(ui_Label5, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button4, 309);
lv_obj_set_height( ui_Button4, 86);
lv_obj_set_x( ui_Button4, 1 );
lv_obj_set_y( ui_Button4, 66 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 3 );
lv_obj_set_y( ui_Label6, 67 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Reset Wifi setup");
lv_obj_set_style_text_font(ui_Label6, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sure1 = lv_checkbox_create(ui_Screen2);
lv_checkbox_set_text(ui_sure1,"I AM SURE");
lv_obj_set_width( ui_sure1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sure1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sure1, -224 );
lv_obj_set_y( ui_sure1, 71 );
lv_obj_set_align( ui_sure1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_sure1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_sure2 = lv_checkbox_create(ui_Screen2);
lv_checkbox_set_text(ui_sure2,"I AM SURE");
lv_obj_set_width( ui_sure2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sure2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sure2, 228 );
lv_obj_set_y( ui_sure2, 67 );
lv_obj_set_align( ui_sure2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_sure2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_batterybar = lv_bar_create(ui_Screen2);
lv_bar_set_value(ui_batterybar,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_batterybar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_batterybar, 150);
lv_obj_set_height( ui_batterybar, 10);
lv_obj_set_x( ui_batterybar, 173 );
lv_obj_set_y( ui_batterybar, 191 );
lv_obj_set_align( ui_batterybar, LV_ALIGN_CENTER );

ui_batterylabel = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_batterylabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batterylabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batterylabel, 167 );
lv_obj_set_y( ui_batterylabel, 165 );
lv_obj_set_align( ui_batterylabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batterylabel,"no data");

ui_batbar1 = lv_bar_create(ui_Screen2);
lv_bar_set_value(ui_batbar1,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_batbar1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_batbar1, 37);
lv_obj_set_height( ui_batbar1, 10);
lv_obj_set_x( ui_batbar1, 264 );
lv_obj_set_y( ui_batbar1, -205 );
lv_obj_set_align( ui_batbar1, LV_ALIGN_CENTER );

ui_BtnRig = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_BtnRig, 200);
lv_obj_set_height( ui_BtnRig, 44);
lv_obj_set_x( ui_BtnRig, -140 );
lv_obj_set_y( ui_BtnRig, 134 );
lv_obj_set_align( ui_BtnRig, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnRig, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnRig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelRig = lv_label_create(ui_BtnRig);
lv_obj_set_width( ui_LabelRig, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRig, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelRig, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelRig,"Switch NINA rig");
lv_obj_set_style_text_font(ui_LabelRig, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_riglabel = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_riglabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_riglabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_riglabel, 120 );
lv_obj_set_y( ui_riglabel, 134 );
lv_obj_set_align( ui_riglabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_riglabel,"Rig: --");

lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnRig, ui_event_BtnRig, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Button2= NULL;
ui_Label3= NULL;
ui_Slider1= NULL;
ui_Label4= NULL;
ui_Slider2= NULL;
ui_Label5= NULL;
ui_Button4= NULL;
ui_Label6= NULL;
ui_sure1= NULL;
ui_sure2= NULL;
ui_batterybar= NULL;
ui_batterylabel= NULL;
ui_batbar1= NULL;
ui_BtnRig= NULL;
ui_LabelRig= NULL;
ui_riglabel= NULL;

}
