// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t *ui_Screen2;
extern void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label3;
extern void ui_event_Slider1( lv_event_t * e);
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Label4;
extern void ui_event_Slider2( lv_event_t * e);
extern lv_obj_t *ui_Slider2;
extern lv_obj_t *ui_Label5;
extern void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_sure1;
extern lv_obj_t *ui_sure2;
extern lv_obj_t *ui_batterybar;
extern lv_obj_t *ui_batterylabel;
extern lv_obj_t *ui_batbar1;
extern void ui_event_BtnRig( lv_event_t * e);
extern lv_obj_t *ui_BtnRig;
extern lv_obj_t *ui_LabelRig;
extern lv_obj_t *ui_riglabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

