// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_ImagingPanel1 = NULL;lv_obj_t *ui_Panel5 = NULL;lv_obj_t *ui_hfrlabel1 = NULL;lv_obj_t *ui_batbar4 = NULL;
// event funtions
void ui_event_ImagingPanel1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_uiGraphPanel, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_uiGraphPanel_screen_init);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagingPanel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_ImagingPanel1, 593);
lv_obj_set_height( ui_ImagingPanel1, 364);
lv_obj_set_x( ui_ImagingPanel1, -1 );
lv_obj_set_y( ui_ImagingPanel1, 38 );
lv_obj_set_align( ui_ImagingPanel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImagingPanel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel5 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel5, 586);
lv_obj_set_height( ui_Panel5, 60);
lv_obj_set_x( ui_Panel5, 0 );
lv_obj_set_y( ui_Panel5, -185 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_hfrlabel1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_hfrlabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hfrlabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hfrlabel1, -1 );
lv_obj_set_y( ui_hfrlabel1, -186 );
lv_obj_set_align( ui_hfrlabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_hfrlabel1,"HFR");
lv_obj_set_style_text_font(ui_hfrlabel1, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batbar4 = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_batbar4,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_batbar4, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_batbar4, 37);
lv_obj_set_height( ui_batbar4, 10);
lv_obj_set_x( ui_batbar4, 264 );
lv_obj_set_y( ui_batbar4, -205 );
lv_obj_set_align( ui_batbar4, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_ImagingPanel1, ui_event_ImagingPanel1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_ImagingPanel1= NULL;
ui_Panel5= NULL;
ui_hfrlabel1= NULL;
ui_batbar4= NULL;

}
