// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_UIGRAPHPANEL_H
#define UI_UIGRAPHPANEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiGraphPanel
extern void ui_uiGraphPanel_screen_init(void);
extern void ui_uiGraphPanel_screen_destroy(void);
extern lv_obj_t *ui_uiGraphPanel;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Status;
extern lv_obj_t *ui_TOTLabel;
extern lv_obj_t *ui_RALabel;
extern lv_obj_t *ui_DECLabel;
extern void ui_event_Panel2( lv_event_t * e);
extern lv_obj_t *ui_Panel2;
extern void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_batbar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

