// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t *ui_Screen5;
extern void ui_event_SkyPanel( lv_event_t * e);
extern lv_obj_t *ui_SkyPanel;
extern lv_obj_t *ui_targettonight;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_guidingchart;
extern lv_obj_t *ui_hfronly;
extern lv_obj_t *ui_filtername;
extern lv_obj_t *ui_totaldone;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_hfrstat;
extern lv_obj_t *ui_totstat;
extern lv_obj_t *ui_batbar3;
extern lv_obj_t *ui_totstat1;
extern lv_obj_t *ui_meridian;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

