// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen3 = NULL;lv_obj_t *ui_ImagingPanel = NULL;lv_obj_t *ui_Panel4 = NULL;lv_obj_t *ui_hfrlabel = NULL;lv_obj_t *ui_starslabel = NULL;lv_obj_t *ui_batbar2 = NULL;
// event funtions
void ui_event_ImagingPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen4_screen_init);
}
}

// build funtions

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagingPanel = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_ImagingPanel, 593);
lv_obj_set_height( ui_ImagingPanel, 364);
lv_obj_set_x( ui_ImagingPanel, -1 );
lv_obj_set_y( ui_ImagingPanel, 38 );
lv_obj_set_align( ui_ImagingPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImagingPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel4 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel4, 586);
lv_obj_set_height( ui_Panel4, 60);
lv_obj_set_x( ui_Panel4, 0 );
lv_obj_set_y( ui_Panel4, -185 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_hfrlabel = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_hfrlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hfrlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hfrlabel, -158 );
lv_obj_set_y( ui_hfrlabel, -186 );
lv_obj_set_align( ui_hfrlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_hfrlabel,"HFR");
lv_obj_set_style_text_font(ui_hfrlabel, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_starslabel = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_starslabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_starslabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_starslabel, 108 );
lv_obj_set_y( ui_starslabel, -187 );
lv_obj_set_align( ui_starslabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_starslabel,"#Stars");
lv_obj_set_style_text_font(ui_starslabel, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batbar2 = lv_bar_create(ui_Screen3);
lv_bar_set_value(ui_batbar2,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_batbar2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_batbar2, 37);
lv_obj_set_height( ui_batbar2, 10);
lv_obj_set_x( ui_batbar2, 264 );
lv_obj_set_y( ui_batbar2, -205 );
lv_obj_set_align( ui_batbar2, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_ImagingPanel, ui_event_ImagingPanel, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
   if (ui_Screen3) lv_obj_del(ui_Screen3);

// NULL screen variables
ui_Screen3= NULL;
ui_ImagingPanel= NULL;
ui_Panel4= NULL;
ui_hfrlabel= NULL;
ui_starslabel= NULL;
ui_batbar2= NULL;

}
