// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_uiGraphPanel = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Status = NULL;lv_obj_t *ui_TOTLabel = NULL;lv_obj_t *ui_RALabel = NULL;lv_obj_t *ui_DECLabel = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Button1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_batbar = NULL;
// event funtions
void ui_event_Panel2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
}
}

void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}
}

// build funtions

void ui_uiGraphPanel_screen_init(void)
{
ui_uiGraphPanel = lv_obj_create(NULL);
lv_obj_clear_flag( ui_uiGraphPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_uiGraphPanel);
lv_obj_set_width( ui_Panel1, 605);
lv_obj_set_height( ui_Panel1, 168);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, -140 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Status = lv_label_create(ui_uiGraphPanel);
lv_obj_set_width( ui_Status, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Status, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Status, 0 );
lv_obj_set_y( ui_Status, -195 );
lv_obj_set_align( ui_Status, LV_ALIGN_CENTER );
lv_label_set_text(ui_Status,"State: waiting");
lv_obj_set_style_text_color(ui_Status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Status, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Status, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TOTLabel = lv_label_create(ui_uiGraphPanel);
lv_obj_set_width( ui_TOTLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TOTLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TOTLabel, 0 );
lv_obj_set_y( ui_TOTLabel, -147 );
lv_obj_set_align( ui_TOTLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TOTLabel,"Total: no data");
lv_obj_set_style_text_color(ui_TOTLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TOTLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TOTLabel, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RALabel = lv_label_create(ui_uiGraphPanel);
lv_obj_set_width( ui_RALabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RALabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RALabel, -160 );
lv_obj_set_y( ui_RALabel, -95 );
lv_obj_set_align( ui_RALabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RALabel,"RA: no data");
lv_obj_set_style_text_color(ui_RALabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RALabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RALabel, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DECLabel = lv_label_create(ui_uiGraphPanel);
lv_obj_set_width( ui_DECLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DECLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DECLabel, 126 );
lv_obj_set_y( ui_DECLabel, -96 );
lv_obj_set_align( ui_DECLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DECLabel,"Dec: no data");
lv_obj_set_style_text_color(ui_DECLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DECLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DECLabel, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_uiGraphPanel);
lv_obj_set_width( ui_Panel2, 612);
lv_obj_set_height( ui_Panel2, 271);
lv_obj_set_x( ui_Panel2, 2 );
lv_obj_set_y( ui_Panel2, 84 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button1 = lv_btn_create(ui_uiGraphPanel);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, -236 );
lv_obj_set_y( ui_Button1, -195 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x161616), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_uiGraphPanel);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -237 );
lv_obj_set_y( ui_Label2, -195 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Setup");
lv_obj_set_style_text_font(ui_Label2, &ui_font_Font13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batbar = lv_bar_create(ui_uiGraphPanel);
lv_bar_set_value(ui_batbar,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_batbar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_batbar, 37);
lv_obj_set_height( ui_batbar, 10);
lv_obj_set_x( ui_batbar, 264 );
lv_obj_set_y( ui_batbar, -205 );
lv_obj_set_align( ui_batbar, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_uiGraphPanel_screen_destroy(void)
{
   if (ui_uiGraphPanel) lv_obj_del(ui_uiGraphPanel);

// NULL screen variables
ui_uiGraphPanel= NULL;
ui_Panel1= NULL;
ui_Status= NULL;
ui_TOTLabel= NULL;
ui_RALabel= NULL;
ui_DECLabel= NULL;
ui_Panel2= NULL;
ui_Button1= NULL;
ui_Label2= NULL;
ui_batbar= NULL;

}
